### ISSUE TITLE
What does `item.qty` do?

### ISSUE THREAD

**Issue by michielbdejong** [m-ld/m-ld-web-starter#1]
In https://github.com/m-ld/m-ld-web-starter/blob/main/form.js#L134 you set `qty` to 1, but when I then set "Quantity" to 2 through the GUI, the result will be:

```js
{
  @id: "cd7739b8",
  qty: 1,
  quantity: "2",
  @type: "item"
}
```

Is by design or was this intended as `quantity: "1"` instead?

**Comment by gsvarovsky** [comment]
Whoops! – Fixed
